### ISSUE TITLE
[Devtools][bug?] htmlspecialchars(): Argument #1 ($string) must be of type string, array given

### ISSUE THREAD

**Issue by skpr-repo** [Laravel-Backpack/addons#44] opened 2022-11-17 16:50 UTC
# Bug report (maybe?)

### What I did

When I visit admin/devtools/model I get this error:

```
htmlspecialchars(): Argument #1 ($string) must be of type string, array given {"view":{"view":"/home/vagrant/code/[...]/resources/views/vendor/backpack/devtools/livewire/modals/publish-modal.blade.php","data":[]},"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): htmlspecialchars(): Argument #1 ($string) must be of type string, array given at /home/vagrant/code/[...]/vendor/laravel/framework/src/Illuminate/Support/helpers.php:123)
[stacktrace]
#0 /home/vagrant/code/[...]/vendor/laravel/framework/src/Illuminate/Support/helpers.php(123): htmlspecialchars()
#1 /home/vagrant/code/[...]/resources/views/vendor/backpack/devtools/livewire/modals/publish-modal.blade.php(19): e()
```

inside resources\views\vendor\backpack\devtools\livewire\modals\publish-modal.blade.php
Logging the $key values inside the foreach loop at row 19, I found out that some keys have an $option = array instead of string. The two keys are "crud" and "pro".

Adding

```
@if(!is_array($option))
<option value="{{ $key }}" wire:key="file_option_{{ $loop->index }}">{{ $option }}</option>
@endif
```

solves the issue.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.7 (cli) (built: Jun 10 2022 12:22:48) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.7, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.39.0@67e674709e1e7db14f304a871481f310822d68c5

### BACKPACK VERSION:
5.4.7@6e1bb116de9f3091530cb9b11edcceb4d252daa8

### Operating System and Server Setup

I encountered the problem above on my Windows 10 machine, Google Chrome latest and my web server is set up using Homestead. MySql 8. composer update to the latest versions. I have a license for backpack pro, devtools and editable-columns, latest version.

Thanks

**Comment by skpr-repo** [comment] 2022-11-21 13:32
When I create and save a new Model (with bottom default checkboxes values) I get this error, but Model and Controller are created successfully:

```
array_filter(): Argument #1 ($array) must be of type array, null given {"exception":"[object] (TypeError(code: 0): array_filter(): Argument #1 ($array) must be of type array, null given at /home/vagrant/code/[...]/vendor/backpack/crud/src/app/Library/CrudPanel/Traits/SaveActions.php:52)
[stacktrace]
#0 /home/vagrant/code/[...]/vendor/backpack/crud/src/app/Library/CrudPanel/Traits/SaveActions.php(52): array_filter()
#1 /home/vagrant/code/[...]/vendor/backpack/crud/src/app/Library/CrudPanel/Traits/SaveActions.php(28): Backpack\\CRUD\\app\\Library\\CrudPanel\\CrudPanel->getSaveActionByOrder()
#2 /home/vagrant/code/[...]/vendor/backpack/crud/src/app/Library/CrudPanel/Traits/SaveActions.php(307): Backpack\\CRUD\\app\\Library\\CrudPanel\\CrudPanel->getFallBackSaveAction()
#3 /home/vagrant/code/[...]/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Backpack\\CRUD\\app\\Library\\CrudPanel\\CrudPanel->setSaveAction()
#4 /home/vagrant/code/[...]/vendor/backpack/devtools/src/Http/Controllers/ModelCrudController.php(272): Illuminate\\Support\\Facades\\Facade::__callStatic()
#5 /home/vagrant/code/[...]/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Backpack\\DevTools\\Http\\Controllers\\ModelCrudController->store()
```

**Comment by pxpm** [comment] 2022-11-23 13:23
Hello @skpr-repo About the first issue I think you may have an outdate file, as we currently don't have any loop on line 19: 

![image](https://user-images.githubusercontent.com/7188159/203556485-cc7c93c7-8a96-49de-a9aa-99bb5df36e53.png)

The loop is on 53:
![image](https://user-images.githubusercontent.com/7188159/203556548-9d07c321-cec9-4eb6-aae4-33ffe75f497e.png)

The contents of `$visibleOptions` are splited in `$project => $options` and this are the contents:

![image](https://user-images.githubusercontent.com/7188159/203556935-0e9ad60a-235e-41db-aeec-5af852810478.png)

As you can see `$project = crud/pro` and the options are `key => value` pairs that we get with `foreach($options as $key => $option`.

Please make sure you are requiring Devtools `^1.2` in your composer.json to get the latest version. You can do a `composer why backpack/devtools` to known the currently required version. 

After you confirm you are in the latest version, please also verify if the last issue persist as I was not able to reproduce it either. 

Cheers 🙏

**Comment by skpr-repo** [comment] 2022-11-23 13:59
Thanks, I don't know why this file wasn't updated. Anyway now I have version 1.2 and it works.
But I still have the other error when I create a new model 
[array_filter(): Argument #1 ($array) must be of type array, null given](https://github.com/Laravel-Backpack/addons/issues/44#issuecomment-1322072204)

**Comment by tabacitu** [comment] 2022-12-05 17:18
Merged, will be tagged later today! 🎉 Thanks guys!

**Closed as completed** 2022-12-05 17:18 UTC
